services:
  - type: web
    name: CREDX-RESUME-ANALYZER-SUITE
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
      python -c "import nltk; nltk.download('punkt', download_dir='nltk_data'); nltk.download('stopwords', download_dir='nltk_data')"
    startCommand: gunicorn app:app
    disks:
      - name: uploads
        mountPath: /opt/render/project/src/uploads
        sizeGB: 1
      - name: nltk-data
        mountPath: /opt/render/project/src/nltk_data
        sizeGB: 1
